In [1]:
import pandas as pd
import math
from sklearn import preprocessing

In [22]:
df = pd.read_csv("train.csv",sep=',')
df['taxi_type']=df['taxi_type'].fillna(df['taxi_type'].value_counts().idxmax())
df['months_of_activity'] = df['months_of_activity'].fillna(df['months_of_activity'].mean())
df['customer_score'] = df['customer_score'].fillna(df['customer_score'].mean())
df['customer_score_confidence'] = df['customer_score_confidence'].fillna(df['customer_score_confidence'].value_counts().idxmax())
df['drop_location_type'] = df['drop_location_type'].fillna(df['drop_location_type'].value_counts().idxmax())
df['ratings_given_by_cust'] = df['ratings_given_by_cust'].fillna(df['ratings_given_by_cust'].mean())
df['num_of_cancelled_trips'] = df['num_of_cancelled_trips'].fillna(math.ceil(df['num_of_cancelled_trips'].mean()))
df['anon_var_1'] = df['anon_var_1'].fillna(math.ceil(df['anon_var_1'].mean()))
df['anon_var_2'] = df['anon_var_2'].fillna(math.ceil(df['anon_var_2'].mean()))
df['anon_var_3'] = df['anon_var_3'].fillna(math.ceil(df['anon_var_3'].mean()))
df['sex'] = df['sex'].map({'Female': 1, 'Male': 0})
abc = df['taxi_type'].unique()
df['taxi_type'] = df['taxi_type'].map({'A':0, 'B':1, 'C':2, 'D':3, 'E':4})
customer_score_confidence = df['customer_score_confidence'].unique()
customer_score_confidence.sort()
df['customer_score_confidence'] = df['customer_score_confidence'].map({customer_score_confidence[i]:i for i in range(len(customer_score_confidence))})
drop_location_type = df['drop_location_type'].unique()
drop_location_type.sort()
#print(drop_location_type)
df['drop_location_type'] = df['drop_location_type'].map({drop_location_type[i]:i for i in range(len(drop_location_type))})

df = df.drop(['id'],axis=1)
df

,distance,taxi_type,months_of_activity,customer_score,customer_score_confidence,drop_location_type,ratings_given_by_cust,num_of_cancelled_trips,anon_var_1,anon_var_2,anon_var_3,sex,pricing_category
0,59.30,2,1.000000,2.80145,1,1,1.18625,0,65.0,50,71,0,2
1,20.68,1,0.000000,2.79222,2,1,1.91750,1,31.0,50,65,0,2
2,64.83,1,1.000000,2.97482,2,0,3.62125,0,65.0,49,84,0,2
3,25.51,2,0.000000,2.90334,0,1,4.76750,2,46.0,43,60,1,3
4,20.16,3,6.000000,2.62301,1,3,2.03875,0,65.0,52,71,1,3
5,16.07,0,0.000000,2.23315,2,0,2.61625,3,65.0,52,66,1,1
6,62.67,0,5.000000,2.91195,1,0,2.70375,1,65.0,59,95,0,1
7,61.80,0,10.000000,2.88819,1,0,2.90375,0,65.0,51,70,1,1
8,50.22,1,10.000000,2.64932,1,1,2.32375,0,87.0,49,82,0,2
9,47.68,4,2.000000,2.62713,2,0,3.85250,0,65.0,46,58,1,3
10,47.79,2,2.000000,2.90698,1,2,1.39625,1,92.0,52,90,0,3
11,18.25,2,5.000000,2.69602,2,1,1.86750,1,65.0,53,77,0,2
12,91.61,1,10.000000,3.09525,1,0,4.12500,0,94.0,50,67,0,3
13,90.96,2,10.000000,2.80145,1,0,1.62000,0,63.0,61,91,0,3
14,63.03,1,3.000000,2.95138,2,0,3.06125,0,65.0,58,85,1,2
15,28.28,0,10.000000,2.81862,2,4,2.92125,1,55.0,55,86,1,1
16,16.97,1,10.000000,3.08221,0,0,1.50125,1,43.0,59,91,0,2
17,75.37,4,0.000000,2.90538,1,0,4.21375,2,35.0,50,73,0,3
18,81.73,1,10.000000,2.91318,2,1,2.92750,0,40.0,50,76,0,1
19,30.00,2,6.014179,2.59192,1,0,2.72000,0,65.0,47,86,1,2
20,30.34,2,2.000000,2.77153,0,0,4.40250,0,65.0,45,66,0,2
21,3.47,1,5.000000,2.54327,0,0,1.27625,1,65.0,54,66,0,2
22,27.32,1,9.000000,2.42415,0,1,2.71000,0,65.0,45,58,0,2
23,29.90,1,3.000000,2.80145,1,0,3.01750,0,65.0,50,70,1,1
24,54.37,2,2.000000,2.84372,1,0,2.02500,1,47.0,50,76,0,3
25,30.79,2,0.000000,2.80145,1,1,1.48125,3,101.0,54,74,1,2
26,31.38,4,10.000000,2.80479,0,0,0.82375,0,65.0,53,88,0,2
27,29.65,3,10.000000,3.08826,0,0,2.71625,1,33.0,57,84,0,3
28,33.14,1,10.000000,2.59571,2,0,2.46125,0,65.0,45,60,0,2
29,55.14,3,10.000000,2.93183,0,0,1.04500,0,65.0,56,89,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
78967,10.47,3,6.000000,2.90164,0,0,2.86250,1,35.0,63,88,0,3
78968,13.29,2,5.000000,2.69374,2,3,2.15875,3,34.0,56,95,0,2
78969,43.50,1,6.000000,2.65869,0,1,1.38250,0,65.0,58,80,0,2
78970,108.21,1,1.000000,3.60307,2,0,2.90000,0,31.0,56,97,0,3
78971,92.94,0,6.000000,2.80145,1,1,3.62125,0,110.0,57,98,0,1
78972,11.72,2,3.000000,3.03778,1,0,2.58750,1,65.0,58,86,0,2
78973,63.65,3,10.000000,2.80693,2,0,3.60125,1,99.0,47,75,1,3
78974,107.32,3,10.000000,3.13175,2,0,1.76250,0,65.0,62,92,1,3
78975,50.75,1,10.000000,3.02401,0,0,2.81625,0,65.0,50,85,0,1
78976,47.14,2,6.000000,2.85494,1,0,2.56625,5,65.0,53,73,0,2
78977,36.84,2,0.000000,2.74683,0,0,2.88125,0,65.0,54,107,0,2
78978,22.81,1,10.000000,2.53681,0,1,2.66000,0,65.0,49,65,1,2
78979,108.14,1,10.000000,3.05961,1,11,3.95250,2,65.0,52,83,0,3
78980,15.44,2,6.014179,2.66567,1,3,1.96500,0,48.0,47,74,1,2
78981,23.18,4,3.000000,2.63218,0,0,1.73375,0,65.0,52,68,0,2
78982,74.20,0,9.000000,2.96172,2,0,2.43875,0,65.0,55,100,0,1
78983,4.67,1,4.000000,2.76448,0,1,3.31250,0,65.0,62,85,1,2
78984,91.79,0,10.000000,3.02311,1,0,3.06875,1,65.0,48,61,1,3
78985,57.19,0,5.000000,2.78598,0,0,2.68500,0,65.0,47,82,0,1
78986,56.58,1,10.000000,3.10025,0,0,2.80375,0,65.0,49,75,1,2
78987,42.25,1,6.000000,3.02773,1,0,2.42375,1,65.0,57,91,1,2
78988,18.42,2,4.000000,2.60492,0,0,1.39250,2,59.0,53,81,1,2
78989,62.06,2,10.000000,2.79133,2,2,3.96875,0,51.0,47,71,0,2
78990,8.30,3,6.014179,2.32079,0,3,3.96500,0,71.0,47,61,0,3
78991,69.29,4,10.000000,2.77887,2,0,1.59000,0,65.0,53,74,0,3
78992,10.69,1,0.000000,2.38653,1,6,3.27250,0,55.0,44,68,0,2
78993,31.58,1,10.000000,2.61104,1,7,1.41125,1,65.0,49,68,1,2
78994,13.11,1,6.000000,2.65354,0,3,3.54375,0,65.0,48,63,0,2
78995,63.79,2,10.000000,2.80145,1,0,3.60125,0,65.0,51,74,0,2
78996,30.46,2,10.000000,2.74367,1,1,2.69250,1,94.0,48,64,0,3

In [3]:
tf=pd.read_csv("test.csv",sep=",")
tf['taxi_type']=tf['taxi_type'].fillna(tf['taxi_type'].value_counts().idxmax())
tf['months_of_activity'] = tf['months_of_activity'].fillna(tf['months_of_activity'].mean())
tf['customer_score'] = tf['customer_score'].fillna(tf['customer_score'].mean())
tf['customer_score_confidence'] = tf['customer_score_confidence'].fillna(tf['customer_score_confidence'].value_counts().idxmax())
tf['drop_location_type'] = tf['drop_location_type'].fillna(tf['drop_location_type'].value_counts().idxmax())
tf['ratings_given_by_cust'] = tf['ratings_given_by_cust'].fillna(tf['ratings_given_by_cust'].mean())
tf['num_of_cancelled_trips'] = tf['num_of_cancelled_trips'].fillna(math.ceil(tf['num_of_cancelled_trips'].mean()))
tf['anon_var_1'] = tf['anon_var_1'].fillna(math.ceil(tf['anon_var_1'].mean()))
tf['anon_var_2'] = tf['anon_var_2'].fillna(math.ceil(tf['anon_var_2'].mean()))
tf['anon_var_3'] = tf['anon_var_3'].fillna(math.ceil(tf['anon_var_3'].mean()))


tf['taxi_type'] = tf['taxi_type'].map({'A':0, 'B':1, 'C':2, 'D':3, 'E':4})
tf['sex'] = tf['sex'].map({'Female': 1, 'Male': 0})
customer_score_confidence = tf['customer_score_confidence'].unique()
customer_score_confidence.sort()
tf['customer_score_confidence'] = tf['customer_score_confidence'].map({customer_score_confidence[i]:i for i in range(len(customer_score_confidence))})
drop_location_type = tf['drop_location_type'].unique()
drop_location_type.sort()
#print(drop_location_type)
tf['drop_location_type'] = tf['drop_location_type'].map({drop_location_type[i]:i for i in range(len(drop_location_type))})
temp = tf['id']
temp.to_csv("output.csv")

tf=tf.drop(['id'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import KFold

y_train= df.iloc[:,-1]
y_train= y_train.astype(float)
X_train = df.drop('pricing_category', axis=1)

X_test = tf




#clf =RandomForestClassifier(n_estimators=100,random_state=0,n_jobs=-1,max_depth=20)
clf = XGBClassifier(n_estimators=400,max_depth = 3,min_child_weight=10,reg_lambda=1,learning_rate=0.1,subsample=0.9, colsample_bytree=0.6,objective= 'multi:softmax',nthread=4)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

#print("accuracy:", metrics.accuracy_score(y_test, y_pred)) 
# scores = cross_val_score(clf, df, y_train, cv=6)
print(np.mean(cross_val_score(clf, X_train, y_train, cv=2)))
# print(scores)

In [55]:
abc = pd.DataFrame({'pricing_category':y_pred})
k = temp.to_frame()
final = k.join(abc)
final.to_csv("out.csv",index=False)